InFlow_Web/Models/ManageBOsViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace strICT.InFlow.Web.Models.ManageBos
{
    public class BusinessObjectDTO
    {
        public int Id { get; set; }

        public string Name { get; set; }


    }

    public class BusinessObjectDetails
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string ViewData { get; set; }

        public string JsonSchema { get; set; }

        public string DefaultData { get; set; }
    }
}

InFlow_Web/Controllers/ManageBOsController.cs
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Schema;
using strict.InFlow.Designer.BODb;
using strict.InFlow.Designer.BODb.Contracts;
using strICT.InFlow.Db.Contracts.InFlow;
using strICT.InFlow.Db.DataContexts;
using strICT.InFlow.Web.Helpers.BO;
using strICT.InFlow.Web.Models;
using strICT.InFlow.Web.Models.ManageBos;
using strICT.InFlow.WFM.BO_Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace strICT.InFlow.Web.Controllers
{
    [Authorize(Roles = "ProcessEditor")]
    public class ManageBOsController : Controller
    {
        BODb _BOdb = new BODb();
        BODdb _BODdb = new BODdb();


        public ActionResult Index()
        {
            List<BusinessObjectDTO> model = new List<BusinessObjectDTO>();
            _BOdb.BusinessObjects.ToList().ForEach(o => model.Add(new BusinessObjectDTO() { Id = o.Id, Name = o.Name }));


            return View(model);
        }


        public ActionResult deleteBO(int id)
        {
            var bo = _BOdb.BusinessObjects.Find(id);

            if (_BOdb.BusinessObjectInstances.Count(r => r.BusinessObjectId == id) == 0)
            {

               // string path = Server.MapPath("~/" + bo.VirtualPath);

                _BOdb.BusinessObjects.Remove(bo);

                _BOdb.SaveChanges();

                //System.IO.File.Delete(path);
            }

            return RedirectToAction("Index");
        }

        private void cleanBOs()
        {
            var bos = _BODdb.BOD_BOs.ToList();

            List<int> ids = new List<int>();
            bos.Where(r => r.LastChange.AddMinutes(10) < DateTime.Now).ToList().ForEach(i => ids.Add(i.Id));

            ids.ForEach(item => _BODdb.BOD_BOs.Remove(_BODdb.BOD_BOs.Find(item)));

            _BODdb.SaveChanges();
        }

        public ActionResult newBO()
        {

            cleanBOs();


            BOD_BO bo = new BOD_BO() { Name = "NEWBO" };
            _BODdb.BOD_BOs.Add(bo);

            _BODdb.SaveChanges();


            BOD_Item root = new BOD_Item() { BO = bo, Name = "schema1", Type = POD_DataTypes._object, Id = 0 };
            _BODdb.BOD_Items.Add(root);
            _BODdb.SaveChanges();


            return RedirectToAction("ViewBO", new { id = bo.Id });
        }

        public ActionResult generateBO(int id)
        {


            Model2JSON mj = new Model2JSON(id);

            string jsonschema = mj.getSchema();
            string jsondata = mj.getDefaultData();

            Model2Html mh = new Model2Html(id);

            string html = mh.getcsHTML();

            BO_BusinessObject bo = new BO_BusinessObject();

            bo.Name = "new BO" + id;
            bo.DefaultData = jsondata;
            bo.JsonSchema = jsonschema;
            bo.ViewData = html;

            _BOdb.BusinessObjects.Add(bo);
            _BOdb.SaveChanges();

            //bo.VirtualPath = "/Views/BORepository/bo" + bo.Id + ".cshtml";
            _BOdb.SaveChanges();

            //writeViewData(bo.VirtualPath, html);

            _BODdb.BOD_BOs.Remove(_BODdb.BOD_BOs.Find(id));
            _BODdb.SaveChanges();

            return RedirectToAction("Details", new { id = bo.Id });
        }

        #region borawdata
        public ActionResult Details(int id)
        {
            BusinessObjectDetails model;

            if (id > 0)
            {
                var bo = _BOdb.BusinessObjects.Find(id);

                //string viewData = readViewData(bo.VirtualPath);

                model = new BusinessObjectDetails() { Id = bo.Id, Name = bo.Name, JsonSchema = bo.JsonSchema, DefaultData = bo.DefaultData , ViewData = bo.ViewData }; // ,ViewData = viewData };
            }
            else
            {
                model = new BusinessObjectDetails() { Id = -1, Name = "Name", DefaultData = "", JsonSchema = "" , ViewData = "" };  // ,ViewData = viewData };
            }

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Details(BusinessObjectDetails model)
        {
            BO_BusinessObject bo;

            bool writeaccess = false;

            if (model.Id > 0)
            {
                bo = _BOdb.BusinessObjects.Find(model.Id);
                writeaccess = (_BOdb.BusinessObjectInstances.Count(r => r.BusinessObjectId == model.Id) == 0);
            }
            else
            {
                bo = new BO_BusinessObject();
                writeaccess = true;
            }


            if (writeaccess)
            {

                bo.Name = model.Name;
                bo.DefaultData = model.DefaultData;
                bo.JsonSchema = model.JsonSchema;
                bo.ViewData = model.ViewData;



                if (model.Id < 0)
                {
                    _BOdb.BusinessObjects.Add(bo);
                }
                _BOdb.SaveChanges();

                /*if (model.Id < 0)
                {
                    bo.VirtualPath = "/Views/BORepository/bo" + bo.Id + ".cshtml";
                    _BOdb.SaveChanges();
                }*/

                //writeViewData(bo.VirtualPath, model.ViewData);
            }

            return RedirectToAction("Index");
        }


        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult PreviewBO(int id)
        {
            var bo = _BOdb.BusinessObjects.Find(id);

            BORender bor = new BORender();


            ViewBOModel model = new ViewBOModel();

            //dynamic model =  new dynamic();// Newtonsoft.Json.JsonConvert.DeserializeObject<dynamic>(bo.DefaultData);
            model.BObjectIdentifier = id;
            //model.BObjectSchema = JObject.Parse(bo.JsonSchema);
            //model.BObjectErrors = null;



            model.ViewData = bor.createHTML(bo.DefaultData , bo.JsonSchema ,bo.ViewData);

            //return View("~/Views/BusinessObject/BusinessObject.cshtml", "~/Views/BusinessObject/_BOLayout.cshtml", model);
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult SubmitBusinessObject(int id)
        {

            var schemastring = _BOdb.BusinessObjects.Find(id).JsonSchema;

         
           // string flat = Request.Form.ToString().Replace("%5b", "[").Replace("%5d", "]");
           // string jsonstring = FlatJson.FlatJsonToJsonTree(flat, schemastring);

            string jsonstring = FlatJson.RequestFormToJsonTree(Request.Form, schemastring);

            JObject data = JObject.Parse(jsonstring);



            JsonSchema schema = JsonSchema.Parse(schemastring);

            IList<string> messages;
            bool valid = data.IsValid(schema, out messages);


            if (valid)
            {
                ViewBag.BObjectIdentifier = id;
                ViewBag.Json = jsonstring;

                Dictionary<string, string> model = new Dictionary<string, string>();
                model.Add("json", jsonstring);

                return PartialView(model);
            }
            else
            {
                BORender bor = new BORender();
                string boview = _BOdb.BusinessObjects.Find(id).ViewData;
                ViewBOModel model = new ViewBOModel();
                //dynamic model = Newtonsoft.Json.JsonConvert.DeserializeObject<dynamic>(jsonstring);
                model.BObjectIdentifier = id;
                // model.BObjectSchema = JObject.Parse(schemastring);
                model.BObjectErrors = new List<string>(messages);
                model.ViewData = bor.createHTML(jsonstring, schemastring ,boview);
               

                return PartialView("PreviewBO", model);
            }

        }

        /*
        private byte[] GetBytes(string str)
        {
            return Encoding.UTF8.GetBytes(str.ToCharArray());
        }

        
        private string GetString(byte[] bytes)
        {
            return Encoding.UTF8.GetString(bytes);
        }*/


        private string readViewData(string path)
        {
            path = Server.MapPath("~/" + path);
            StreamReader streamReader = new StreamReader(path);

            string file = streamReader.ReadToEnd();

            streamReader.Close();
            return file;
        }


        private void writeViewData(string path, string data)
        {
            path = Server.MapPath("~/" + path);
            using (StreamWriter outfile = new StreamWriter(path))
            {
                outfile.Write(data);

                outfile.Close();
            }
        }

        #endregion borawdata

        #region bodesigner
        public ActionResult ViewBO(int id)
        {
            var root = _BODdb.BOD_Items.Where(r => r.ParentItem_Id == null && r.BOD_BO_Id == id).First();

            BOD_Item_Model m = createModel(root);


            return View(m);
        }

        public ActionResult ItemDetail(int boid, int id, int parentId)
        {
            BOD_Item_Model m;

            var parent = _BODdb.BOD_Items.Find(boid, parentId);
            if (id < 0)
            {
                m = new BOD_Item_Model() {IsArray = parent.Type == POD_DataTypes._array ,boid = boid, Id = -1, Name = "", Type = POD_DataTypes._string, ChildItems = new List<BOD_Item_Model>(), ParentId = parentId };
            }
            else
            {
                var item = _BODdb.BOD_Items.Where(r => r.Id == id && r.BOD_BO_Id == boid).First();
                m = new BOD_Item_Model() { IsArray = parent.Type == POD_DataTypes._array, boid = boid, Id = item.Id, Name = item.Name, Type = item.Type, ChildItems = new List<BOD_Item_Model>(), ParentId = item.ParentItem_Id };

            }

            return PartialView(m);
        }

        public ActionResult DeleteItem(int boid, int id)
        {
            var item = _BODdb.BOD_Items.Find(boid, id);


            deleteItemRec(item);

            _BODdb.SaveChanges();

InFlow_Web/Views/ManageBOs/Details.cshtml
@model strICT.InFlow.Web.Models.ManageBos.BusinessObjectDetails


<div class="page-header"> <h1><small>Business Objects</small><br />Edit BO-Raw Data</h1></div>

<script src="~/Scripts/CodeMirror/codemirror.js"></script>
<link href="~/Scripts/CodeMirror/codemirror.css" rel="stylesheet" />
<script src="~/Scripts/CodeMirror/xml.js"></script>
<script src="~/Scripts/CodeMirror/javascript.js"></script>


@using (Html.BeginForm("Details", "ManageBOS", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary()
    @Html.HiddenFor(m => Model.Id)
    
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-1 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    
     <div class="form-group">
        @Html.LabelFor(m => m.ViewData, new { @class = "col-md-1 control-label" })
        <div class="col-md-10">
            @*
    @Html.TextAreaFor(m => m.ViewData, 10, 350,new { @class = "form-control" })*@
            <div style="border-top: 1px solid black; border-bottom: 1px solid black;">
                @Html.TextAreaFor(m => m.ViewData ,new {  })
                </div>
        </div>
    </div>
 
    <div class="form-group">
        @Html.LabelFor(m => m.JsonSchema ,new { @class = "col-md-1 control-label" })
        <div class="col-md-10">
            <div style="border-top: 1px solid black; border-bottom: 1px solid black;">
                @Html.TextAreaFor(m => m.JsonSchema, new { })
                </div>
            </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(m => m.DefaultData, new { @class = "col-md-1 control-label" })
        <div class="col-md-10">
            <div style="border-top: 1px solid black; border-bottom: 1px solid black;">
                @Html.TextAreaFor(m => m.DefaultData, new { @class = "form-control" })
                </div>
            </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-offset-1 col-md-10">
            <input type="submit" class="btn btn-default" value="Save" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    var myCodeMirrorViewData = CodeMirror.fromTextArea(document.getElementById('ViewData'), {
        height: "350px",
        mode: "xml",
        continuousScanning: 500,
        lineNumbers: true
    });

    var myCodeMirrorJsonSchema = CodeMirror.fromTextArea(document.getElementById('JsonSchema'), {
        height: "350px",
        mode: "javascript",
        continuousScanning: 500,
        lineNumbers: true
    });

    var myCodeMirrorJsonData = CodeMirror.fromTextArea(document.getElementById('DefaultData'), {
        height: "150px",
        mode: "javascript",
        continuousScanning: 500,
        lineNumbers: true
    });
</script>
}

InFlow_Web/Views/ManageBOs/Index.cshtml
@model IEnumerable<strICT.InFlow.Web.Models.ManageBos.BusinessObjectDTO>


<div class="page-header"> <h1><small>Projects</small><br />Business Objects</h1></div>


<div class="row">
    <div class="col-md-12">
        <table class="table table-striped">
            <tr>
                <th>Id</th>
                <th>Name</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>
                        @item.Name
                        @*@Html.ActionLink(item.Name, "Details", new { id = item.Id }) @Html.ActionLink(" ", "PreviewBO", new { id = item.Id }, new { @class = "glyphicon glyphicon-eye-open" })*@
                        @Html.ActionLink(" ", "Details", new { id = item.Id }, new { @class = "glyphicon glyphicon-pencil", @title = "edit business object" })
                        @Html.ActionLink(" ", "deleteBO", new { id = item.Id }, new { @class = "glyphicon glyphicon-remove" , @title="delete business object"})
                         <a href="#" class="glyphicon glyphicon-eye-open" title="preview business object" onclick="showBO('@Url.Action("PreviewBO", new { id = item.Id })')"></a>
                       

                    </td>
                </tr>
            }
        </table>
        <div style="text-align:right">
            @Html.ActionLink("Create new Business Object", "newBO", new { }, new { @class = "btn btn-default" })
        </div>
    </div>
</div>


<div id="myModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <p></p>
            </div>
            <div class="modal-body">
                <div id="bocontent"> </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>

    <script type="text/javascript">

        function showBO(link) {



            $("#bocontent").load(link, function (responseTxt, statusTxt, xhr) {
                if (statusTxt == "success")
                    $('#myModal').modal({ show: true });
                if (statusTxt == "error")
                    alert("Error: " + xhr.status + ": " + xhr.statusText);
            });
        }


        function DoAjaxPostAndMore(btnClicked) {
            var $form = $(btnClicked).parents('form');

            $.ajax({
                type: "POST",
                url: $form.attr('action'),
                data: $form.serialize(),
                error: function (xhr, status, error) {
                    //do something about the error
                    alert("errro");
                },
                success: function (response) {
                    //do something with response
                    //$('#myModal').modal('hide');
                    $('#bocontainer').replaceWith(response)
                }
            });

            return false;// if it's a link to prevent post

        }

    </script>
}

InFlow_Web/Views/ManageBOs/ItemDetail.cshtml
@model strICT.InFlow.Web.Models.BOD_Item_Model


@using (Html.BeginForm("ItemDetail", "ManageBOs", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.boid)
    @Html.HiddenFor(model => model.ParentId)

    <div class="panel panel-primary">
        <div class="panel-heading">Edit Property</div>
        <div class="panel-body">
            <table class="table table-striped">
                <tr>
                    <td>Name</td>
                    <td>@Html.TextBoxFor(m => m.Name, new { @class = "form-control" })</td>
                </tr>
                <tr>
                    <td>Type</td>
                    <td>@Html.DropDownListFor(m => m.Type_String, Model.Types, new { @class = "form-control" })</td>
                </tr>
            </table>
        </div>
        <div class="panel-footer text-right">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>


}

InFlow_Web/Views/ManageBOs/PreviewBO.cshtml
@model strICT.InFlow.Web.Models.ViewBOModel
<div id="bocontainer">

    @if (Model.BObjectErrors != null)
    {
        <p><b>Validation Errors:</b></p>
        <ul>


            @foreach (var i in Model.BObjectErrors)
            {
                <li>@i</li>
            }
        </ul>

        <hr />
    }

    @using (Html.BeginForm("SubmitBusinessObject", "ManageBOs", new { id = Model.BObjectIdentifier, taskId = ViewBag.TaskId }, FormMethod.Post, new { }))
    {
        <div id="bocontainer">
            @Html.Raw(Model.ViewData)

            <br />
            <input type="button" value="Submit" onclick="DoAjaxPostAndMore(this)" class="btn btn-default" />
        </div>
    }

    <script type="text/javascript">

 function validatenumber(evt) {
     var theEvent = evt || window.event;
     var key = theEvent.keyCode || theEvent.which;
     key = String.fromCharCode(key);
     var regex = /[0-9]|\.|\,/;
     if (!regex.test(key)) {
         theEvent.returnValue = false;
         if (theEvent.preventDefault) theEvent.preventDefault();
     }
 }

    function validateinteger(evt) {
        var theEvent = evt || window.event;
        var key = theEvent.keyCode || theEvent.which;
        key = String.fromCharCode(key);
        var regex = /[0-9]/;
        if (!regex.test(key)) {
            theEvent.returnValue = false;
            if (theEvent.preventDefault) theEvent.preventDefault();
        }
    }

    </script>

</div>

InFlow_Web/Views/ManageBOs/SubmitBusinessObject.cshtml
@model System.Collections.Generic.Dictionary<string,string>

<h2> Submitted JSON Data </h2>
<br />
<p>@Model["json"]</p>

<br />
<a href="#" class="btn btn-default" onclick="$('#myModal').modal('hide')">Close</a>

InFlow_Web/Views/ManageBOs/ViewBO.cshtml
@model strICT.InFlow.Web.Models.BOD_Item_Model



@{
    ViewBag.Title = "ViewBO";
}

<div class="page-header"> <h1><small>Business Objects</small><br />Design new Business Object</h1></div>


<div class="row">
    <div class="col-md-4">

        @Html.Partial("_Item", Model)
        @Ajax.ActionLink(" Item", "ItemDetail", new { boid = Model.boid, id = -1, parentId = Model.Id }, new AjaxOptions { UpdateTargetId = "ItemDiv", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }, new { @class = "glyphicon glyphicon-plus" , @title="add new root-item"})
    </div>

    <div class="col-md-8">

        <div id="ItemDiv"></div>

    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div style="text-align: left">
            <br/>
            @Html.ActionLink("Generate Business Object", "generateBO", new { id = Model.boid }, new { @class = "btn btn-default" })
        </div>

    </div>
</div>






@section scripts
{

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    @Scripts.Render("~/bundles/jqueryval")
}

InFlow_Web/Views/ManageBOs/_Item.cshtml
@model strICT.InFlow.Web.Models.BOD_Item_Model

<ul>
   @* @if (Model.Type != BODesigner.Contracts.POD_DataTypes._array)
    {*@
        @foreach (var item in Model.ChildItems)
        {
            <li>
                @item.Name
                @Ajax.ActionLink(" ", "ItemDetail", new { boid = item.boid, id = item.Id, parentId = item.ParentId }, new AjaxOptions { UpdateTargetId = "ItemDiv", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }, new { @class = "glyphicon glyphicon-pencil", @title="edit item" })
                @if (item.Type == strict.InFlow.Designer.BODb.Contracts.POD_DataTypes._object)
                {
                    @Ajax.ActionLink(" ", "ItemDetail", new { boid = item.boid, id = -1, parentId = item.Id }, new AjaxOptions { UpdateTargetId = "ItemDiv", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }, new { @class = "glyphicon glyphicon-plus", @title = "add sub-item" })

                }
                @if (Model.Type != strict.InFlow.Designer.BODb.Contracts.POD_DataTypes._array)
                {
                    @Html.ActionLink(" ", "DeleteItem", new { boid = item.boid, id = item.Id }, new { @class = "glyphicon glyphicon-remove", @title = "remove item" }) 
                }

                @Html.Partial("_Item", item)
            </li>
        }
    @*}*@
</ul>