InFlow_Web/Controllers/PDesignerController.cs
using strict.InFlow.Designer.Db;
using strict.InFlow.Designer.Db.Contracts;
using strICT.InFlow.Db.Contracts.InFlow;
using strICT.InFlow.Db.DataContexts;
using strICT.InFlow.Web.Models.PDesignerViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace strICT.InFlow.Web.Controllers
{
    [Authorize(Roles = "ProcessEditor")]
    public class PDesignerController : Controller
    {
        PDesignerDb _db = new PDesignerDb();
        InFlowDb _idb = new InFlowDb();
        //
        // GET: /Designer/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewProcess(int processid, int edit)
        {
            ViewBag.ProcessId = processid;

            var modelversion = _idb.WS_ModelVersions.First(result => result.PD_ProcessId == processid);

            ViewBag.Name = modelversion.WS_Project.Name;
            ViewBag.Version = modelversion.Version;
            ViewBag.Edit = 0;
            ViewBag.ProjectId = modelversion.WS_ProjectId;

            if (edit == 1)
            {
                var processmodel = _db.PD_Processes.Find(processid);
                if (processmodel.LockedBy == null)
                {
                    processmodel.LockedBy = User.Identity.Name;
                    _db.SaveChanges();
                    ViewBag.Edit = 1;
                }else if(processmodel.LockedBy.Equals(User.Identity.Name))
                {
                    ViewBag.Edit = 1;
                }   
            }

            return View();
        }

        [OutputCache(Location = System.Web.UI.OutputCacheLocation.None)]
        public ActionResult _EditMessageTypesList(int processid, int edit)
        {
            List<PD_MessageTypeDTO_ViewModel> Model = new List<PD_MessageTypeDTO_ViewModel>();

            var msgtypes = _db.PD_MessageTypes.Where(result => result.PD_Process_Id == processid).ToList();
            foreach (var i in msgtypes)
            {
                var type = new PD_MessageTypeDTO_ViewModel() { Id = i.Id, PD_Process_Id = i.PD_Process_Id, Name = i.Name };
                Model.Add(type);
            }
            ViewBag.ProcessId = processid;
            ViewBag.Edit = edit;
          
            return PartialView(Model);
        }


        [OutputCache(Location = System.Web.UI.OutputCacheLocation.None)]
        public ActionResult _EditMessageType(int processid, int id, int edit)
        {
            PD_MessageTypeDTO_ViewModel model;
            if (id > 0)
            {
                var i = _db.PD_MessageTypes.Find(processid, id);

                model = new PD_MessageTypeDTO_ViewModel() { Id = i.Id, PD_Process_Id = i.PD_Process_Id, Name = i.Name, Parameters = new List<PD_Parameter_ViewModel>() };

                model.Parameters = listofStringParametersToViewModel(processid, i.Parameters);
            }
            else
            {
                model = new PD_MessageTypeDTO_ViewModel() { PD_Process_Id = processid, Name = "New", Parameters = new List<PD_Parameter_ViewModel>() };
            }

            ViewBag.Edit = edit;
            model.newName = model.Name;
            return PartialView(model);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _EditMessageType(PD_MessageTypeDTO_ViewModel model)
        {
             var _p = _db.PD_Processes.Find(model.PD_Process_Id);
             if (User.Identity.Name.Equals(_p.LockedBy))
             {
                 PD_MessageType type;
                 if (model.Id >= 0)
                 {
                     type = _db.PD_MessageTypes.Find(model.PD_Process_Id, model.Id);
                 }
                 else
                 {
                     type = new PD_MessageType() { PD_Process_Id = model.PD_Process_Id };
                     type.Id = IdHelper.getMessageTypeId(_db, model.PD_Process_Id);
                 }
                 type.Name = model.newName;
                 
                 /*
                 string[] para = model.Parameters.Split(',');
                 type.Parameters = new PersistableStringCollection();
                 para.ToList().ForEach(i => type.Parameters.Add(i));*/

                 if (model.Id < 0)
                 {
                     _db.PD_MessageTypes.Add(type);
                 }
                 else
                 {
                     var messages = _db.PD_Messages.Where(result => result.PD_MessageType_Id == type.Id && result.PD_Process_Id == type.PD_Process_Id);
                     messages.ToList().ForEach(i => updateGlobalparameters(i));
                 }

                 _db.SaveChanges();

                 return RedirectToAction("ViewProcess", new { processid = model.PD_Process_Id , edit = 1});
             }
             else
             {
                 return null;
             }
        }


        [OutputCache(Location = System.Web.UI.OutputCacheLocation.None)]
        public ActionResult _DeleteMessageType(int processid, int id)
        {
             var _p = _db.PD_Processes.Find(processid);
             if (User.Identity.Name.Equals(_p.LockedBy))
             {
                 var type = _db.PD_MessageTypes.Find(processid, id);                 
                 _db.PD_MessageTypes.Remove(type);
                 //var message = _db.PD_Messages.Find(processid);
                 try
                 {           
                     var subjects = _db.PD_Subjects.Where(x => x.PD_Process_Id == processid).ToList();
                     var messageTypes = _db.PD_MessageTypes.Where(x => x.PD_Process_Id == processid).ToList();
                     int repeatedTimes = 0;
                     foreach(var i in type.Parameters){
                         foreach(var j in messageTypes){
                             if(j.Parameters.Contains(i))repeatedTimes++;
                         }
                         if(repeatedTimes==1){
                             var param = _db.PD_Parameters.Find(processid, i);
                             _db.PD_Parameters.Remove(param);
                             foreach(var j in subjects){
                                 if(j.GlobalParameters.Contains(i)) j.GlobalParameters.Remove(i);
                             }
                         }
                         repeatedTimes = 0;
                     }                     
                     _db.SaveChanges();
                 }
                 catch
                 {
                     string x = "$('#myModalErrorMessage').modal('toggle'); $('#myModalErrorMessage').modal('show');";                     
                     return JavaScript(x);
                 }
                 ViewBag.Edit = 1;
                 return RedirectToAction("_EditMessageTypesList", new { processid = processid , edit = 1});
             }
             else
             {
                 return null;
             }
        }


        [OutputCache(Location = System.Web.UI.OutputCacheLocation.None)]
        public ActionResult _DeleteAllMessageTypes(int processid)
        {
            var _p = _db.PD_Processes.Find(processid);
            if (User.Identity.Name.Equals(_p.LockedBy))
            {
                var toDelete = _db.PD_MessageTypes.Where(result => result.PD_Process_Id == processid);
                _db.PD_MessageTypes.RemoveRange(toDelete);
                //var message = _db.PD_Messages.Find(processid);
                try
                {
                    _db.SaveChanges();
                }
                catch
                {
                    string x = "$('#myModalErrorMessage').modal('toggle'); $('#myModalErrorMessage').modal('show');";
                    return JavaScript(x);
                }
                ViewBag.Edit = 1;
                return RedirectToAction("_EditMessageTypesList", new { processid = processid, edit = 1 });
            }
            else
            {
                return null;
            }
        }


        [OutputCache(Location = System.Web.UI.OutputCacheLocation.None)]
        public ActionResult _EditSubject(int processid, int subjectid, int edit)
        {
            var subject = _db.PD_Subjects.Find(processid, subjectid);
            PD_Subject_ViewModel model = new PD_Subject_ViewModel() { PD_Process_Id = subject.PD_Process_Id, Id = subject.Id, Name = subject.Name, MultiSubject = subject.MultiSubject, ExternalSubject = subject.ExternalSubject, CanBeStarted = subject.CanBeStarted };
            if (subject.ExternalSubject)
            {
                
                List<ES_ViewModel> sList = new List<ES_ViewModel>();

             //   List<P_ProcessSubject> PSList = _idb.P_ProcessSubjects.Where(x => x.Process_Id != processid && x.ExternalSubject == 0).ToList<P_ProcessSubject>();

                List<PD_Subject> PSList = _db.PD_Subjects.Where(x => x.PD_Process_Id != processid && x.ExternalSubject == false).ToList<PD_Subject>();
                try
                {
                    PSList.ForEach(x => sList.Add(new ES_ViewModel(x.PD_Process_Id + "|" + x.Id, x.PD_Process.Name + " - " + x.Name)));
                    model.ExternalSources = sList;
                    int pid = Int32.Parse(subject.ExternalSubjectId.Split('|')[0]);
                    int sid = Int32.Parse(subject.ExternalSubjectId.Split('|')[1]);
                    PD_Subject es = _db.PD_Subjects.Where(x => x.Id == sid && x.PD_Process_Id == pid).FirstOrDefault();
                    model.ExternalSubjectSource = new ES_ViewModel(subject.ExternalSubjectId, es.PD_Process.Name + " - " + es.Name);
                }
                catch (Exception e) { }
            }
            
            ViewBag.Edit = edit;
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _EditSubject(PD_Subject_ViewModel model)
        {

InFlow_Web/Views/PDesigner/ViewSubject.cshtml
@section stylesheets
{
    @Styles.Render("~/Content/pdesigner.css")
}

<script type="text/javascript">
    var processId = @ViewBag.ProcessId;
    var Edit = @ViewBag.Edit;
    var subjectId = @ViewBag.SubjectId;
    var URL = '@Url.Action("Index", "PDesigner", null, Request.Url.Scheme)';
    URL = URL.replace('PDesigner','');
    var apiURL = URL + 'PDesignerAPI/';
</script>

<div class="page-header">
    <h1><small>S-BPM Process Designer</small><br />@Html.ActionLink(" ", "ViewProcess", new { processid = ViewBag.ProcessId, edit = ViewBag.Edit }, new { @class = "glyphicon glyphicon-arrow-left" }) Subject @ViewBag.Name</h1>
    @if (ViewBag.Edit == 1)
    {
        <span class="label label-danger">Edit Mode</span>
    }
    else
    {
        <span class="label label-success">Read Only Mode</span>
    }
</div>



<div class="row">
    <div class="col-md-1">
        <div class="pdesignertools">

            @if (ViewBag.Edit == 1)
            {
                <select name="pdesignertools" id="pdesignertools" size="3">
                    <option selected>Function</option>
                    <option>Send</option>
                    <option>Receive</option>
              

                </select>
                <p></p>

                <a title="AddState" href="#" onclick="$('#pdesignersubjectcontainer').dblclick();return false;" class="btn btn-default btn-xs">Insert State</a>


            }
            <hr />
            @Ajax.ActionLink("Parameters", "_EditGlobalParameters", new { processid = ViewBag.ProcessId, ViewBag.SubjectId, edit = ViewBag.Edit },
                  new AjaxOptions
                                        {
                                            UpdateTargetId = "pdesignerconfig",
                                            InsertionMode = InsertionMode.Replace,
                                            HttpMethod = "GET"
                                        }
                                        , new { @class = "btn btn-default btn-xs" })
            <hr />
         @Ajax.ActionLink("Refinements", "_AddRefinement", new { processid = ViewBag.ProcessId, ViewBag.SubjectId, edit = ViewBag.Edit },
                  new AjaxOptions
                                        {
                                            UpdateTargetId = "pdesignerconfig",
                                            InsertionMode = InsertionMode.Replace,
                                            HttpMethod = "GET"
                                        }
                                        , new { @class = "btn btn-default btn-xs" })
        <hr />
            <hr /><br><br><br><br>
            <a title="Reset all the subject" href="#" onclick="showList2('resetSubject()');return false;" class="btn btn-default btn-xs">Reset Subject</a>

        </div></div>
    <div class="col-md-7">
        <div id="pdesignersubjectcontainer" class="window"></div>
    </div>
    <div class="col-md-4">
        <div id="pdesignerconfig" style="padding-left:10px"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-4" style="display:none;">
        <ul id="pdesignerlog"><li>logs</li></ul>
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/jquery.jsPlumb-1.5.5-min.js"></script>
    <script src="~/Scripts/pdesigner.subject.js"></script>
    <script src="~/Scripts/jquery.ui.touch-punch.min.js"></script>

<script type="text/javascript">
    function validatenumber(evt) {
        var theEvent = evt || window.event;
        var key = theEvent.keyCode || theEvent.which;
        key = String.fromCharCode(key);
        var regex = /[0-9]|\.|\,/;
        if (!regex.test(key)) {
            theEvent.returnValue = false;
            if (theEvent.preventDefault) theEvent.preventDefault();
        }
    }

    function validateinteger(evt) {
        var theEvent = evt || window.event;
        var key = theEvent.keyCode || theEvent.which;
        key = String.fromCharCode(key);
        var regex = /[0-9]/;
        if (!regex.test(key)) {
            theEvent.returnValue = false;
            if (theEvent.preventDefault) theEvent.preventDefault();
        }
    }

    function showList2(javaAction){              
        //listbut.onclick = $('#link').click();
        document.getElementById("listbut").setAttribute("onclick", javaAction);
        $('#delete1').modal('show'); 
    }

</script>

}

<div id="myModalTimeoutErrorMessage" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <p></p>
            </div>
            <div class="modal-body">
                <div id="formcontent"><center> You need to use the dd:hh:mm (days, hours and minutes) format in order to save the timeout. For example 03:21:33 (3 days, 21 hours and 33 minutes) </center></div>
            </div>
        </div>
    </div>
</div>

<div id="delete1" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <center>Are your sure you want to delete?</center>
            </div>
            <div class="modal-body" align="center">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button id="listbut" type="button" class="btn btn-danger btn-ok" data-dismiss="modal">Delete</button>
            </div>
        </div>
    </div>
</div>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" onclick="window.location.reload()" data-dismiss="modal">×</button>
                <p></p>
            </div>
            <div class="modal-body">
                <div id="formcontent"><center> Wrong action, cannot connect same state </center></div>
            </div>
        </div>
    </div>
</div>

InFlow_Web/Views/PDesigner/_EditMessage.cshtml
@model strICT.InFlow.Web.Models.PDesignerViewModels.PD_Message_ViewModel

@using (Html.BeginForm("_EditMessage", "PDesigner", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="panel panel-primary">
        <div class="panel-heading">Message @Model.Id</div>
        <div class="panel-body">
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.PD_Process_Id)
            @* @Html.HiddenFor(model => model.SelectedMessageType)
            *@
            <table class="table table-striped">
                <tr>
                    <td>MessageType</td>
                    <td>@Html.DropDownListFor(model => model.SelectedMessageType, Model.AvailableMessageTypes, new { @class = "form-control" })</td>
                </tr>
            </table>
            <div class="panel-footer text-right">
                
                <a title="Cancel" href="#" onclick="clearConfigPanel();return false;" class="btn btn-warning">Cancel</a>
                @if (ViewBag.Edit == 1)
                {
                    <input type="submit" value="Save" class="btn btn-success" />
                    @Ajax.ActionLink("Create new", "_EditMessageTypesList", new { processid = Model.PD_Process_Id, edit = 1 },
                    new AjaxOptions
                                        {
                                            UpdateTargetId = "pdesignerconfig",
                                            InsertionMode = InsertionMode.Replace,
                                            HttpMethod = "GET"
                                        }
                                        , new { @class = "btn btn-primary", style = "float:left" })
                }
            </div>
        </div>
    </div>
}

InFlow_Web/Views/PDesigner/_EditMessageParameter.cshtml
@model strICT.InFlow.Web.Models.PDesignerViewModels.PD_MessageParameter_ViewModel

@using (Html.BeginForm("_EditMessageParameter", "PDesigner", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
<div class="panel panel-primary">
    <div class="panel-heading">Edit Parameter</div>
    <div class="panel-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor( m => Model.Process_Id)
        @Html.HiddenFor(m => Model.Message_Type_Id)
        @Html.HiddenFor(m => Model.previousName)
        @Html.HiddenFor(m => Model.messageName)
        <table class="table table-striped">
            <tr>
                <td>
                    Name                    
                </td>
                <td>
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @id = "newName" })
                </td>               
            </tr>
            <tr>
                <td>
                    Type
                </td>
                <td>
                    @Html.DropDownListFor(m => m.Type, Model.AvailableTypes, new { @class = "form-control", @id = "typeList" })
                </td>
            </tr>
            <tr>
                <td>
                    Default Value
                </td>
                <td>
                    @if (Model.Type == "bobasic")
                    {
                        @* @Html.TextBoxFor(m => Model.DefaultValue, new { @class = "form-control", @id = "defaultString", @style = "display:none" })*@
                        <div id="parametereditor" style="display:none"> </div>

                        @Html.DropDownListFor(m => m.SelectedBO, Model.AvailableBOs, new { @class = "form-control", @id = "defaultBO", @style = "display:block" })
                    }
                    else
                    {
                        @* @Html.TextBoxFor(m => Model.DefaultValue, new { @class = "form-control", @id = "defaultString", @style = "display:block" })*@
                        <div id="parametereditor" style="display:block">
                           @{
                        Dictionary<string, string> partialmodel = new Dictionary<string, string>();
                        partialmodel.Add("type", Model.Type);
                        partialmodel.Add("value", Model.DefaultValue);
                            }

                            @Html.Partial("_GetParameterValueEditor", partialmodel)

                        </div>

                        @Html.DropDownListFor(m => m.SelectedBO, Model.AvailableBOs, new { @class = "form-control", @id = "defaultBO", @style = "display:none" })
                    }
                </td>
            </tr>
        </table>
        <div class="panel-footer text-right" id="change">
            @Ajax.ActionLink("Back", "_EditMessageType", new { processid = Model.Process_Id, id = Model.Message_Type_Id, edit = ViewBag.Edit },
                  new AjaxOptions
                                        {
                                            UpdateTargetId = "pdesignerconfig",
                                            InsertionMode = InsertionMode.Replace,
                                            HttpMethod = "GET"
                                        }
                               , new { @class = "btn btn-warning" })
            @if (ViewBag.Edit == 1)
            {
                @*<input type="submit" value="Save" class="btn btn-success"/>*@
                <input type="button" value="Save" onclick="replace()" class="btn btn-success" />
            }
        </div>


 <script type="text/javascript">

    function checkTypeNow(type) {
        if (type == "bobasic") {
            document.getElementById('parametereditor').style.display = 'none';
            document.getElementById('defaultBO').style.display = 'block';
        }
        else {
            // document.getElementById('parametereditor').innerHTML = '<p> abc </p>';
            actionstring = '@Url.Action("_GetParameterValueEditor")' + '?type=' + type
            if (type == 'boolean')
                actionstring = actionstring + '&value=True'
            else
                actionstring = actionstring + '&value=0'

            $.ajax({
                type: "GET",
                url: actionstring,
                error: function (xhr, status, error) {
                    //do something about the error
                    alert("errro");
                },
                success: function (response) {
                    //do something with response
                    //$('#myModal').modal('hide');
                    // $('#bocontainer').replaceWith(response)
                    document.getElementById('parametereditor').innerHTML = response;

                }
            });

            document.getElementById('parametereditor').style.display = 'block';
            document.getElementById('defaultBO').style.display = 'none';
        }
    }


    $('select#typeList').change(function () {
        checkTypeNow($(this).val());
    })

    var EMP = '@Ajax.ActionLink("Save", "_EditMessageParameterNoSubmit", new { processid = Model.Process_Id, Name = "newName", previousName = Model.previousName, messageTypeId = Model.Message_Type_Id, defaultv = "newDefault", Type = "newType", messageName = Model.messageName, ft = true }, new AjaxOptions { UpdateTargetId = "pdesignerconfig", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }, new { @class = "btn btn-success", @style = "display:none", @id = "probaclick" })';
    function replace() {
        EMP = EMP.replace("newName", document.getElementById('newName').value);
        EMP = EMP.replace("newType", document.getElementById('typeList').value);
        if (document.getElementById('typeList').value == "bobasic")
        {
            var e = document.getElementById('defaultBO');
            //var eSel = e.options[e.selectedIndex].text;
            var eSel = e.options[e.selectedIndex].value;
            var dv = "{\"bo\": " + eSel + ",  \"boi\": -1}";
            EMP = EMP.replace("newDefault", eSel);
        } else {
            EMP = EMP.replace("newDefault", document.getElementById('DefaultValue').value);
        }
        //$("#change").append(EMP);
        //$("#change").html(EMP);
        var element = null;
        element = document.getElementById("probaclick");
        if (element == null) $("#change").append(EMP);
        $('#probaclick').click();
    }

    var EMP2 = '@Ajax.ActionLink("Save", "_EditMessageParameterNoSubmit", new { processid = Model.Process_Id, Name = "newName", previousName = Model.previousName, messageTypeId = Model.Message_Type_Id, defaultv = "newDefault", Type = "newType", messageName = Model.messageName, ft = false }, new AjaxOptions { UpdateTargetId = "pdesignerconfig", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }, new { @class = "btn btn-success", @style = "display:none", @id = "probaclick2" })';
    function replace2() {
        EMP2 = EMP2.replace("newName", document.getElementById('newName').value);
        EMP2 = EMP2.replace("newType", document.getElementById('typeList').value);
        if (document.getElementById('typeList').value == "bobasic") {
            var e = document.getElementById('defaultBO');
            var eSel = e.options[e.selectedIndex].value;
            var dv = "{\"bo\": " + eSel + ",  \"boi\": -1}";
            EMP2 = EMP2.replace("newDefault", eSel);
        } else {
            EMP2 = EMP2.replace("newDefault", document.getElementById('DefaultValue').value);
        }
        var element = null;
        element = document.getElementById("probaclick2");
        if (element == null) $("#change").append(EMP2);
        $('#probaclick2').click();
    }

  </script>

    </div>
</div>
}

InFlow_Web/Views/PDesigner/_EditReceiveState.cshtml
@model strICT.InFlow.Web.Models.PDesignerViewModels.PD_ReceiveState_ViewModel

@using (Html.BeginForm("_EditReceiveState", "PDesigner", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="panel panel-primary">
        <div class="panel-heading">Receive State @Model.Name</div>
        <div class="panel-body">
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.PD_Process_Id)
            @Html.HiddenFor(model => model.PD_Subject_Id)

            <table class="table table-striped">
                <tr>
                    <td>Name</td>
                    <td>@Html.TextBoxFor(model => model.Name, new { @class = "form-control" })</td>
                </tr>
                <tr>
                    <td>StartState</td>
                    <td>@Html.EditorFor(model => model.StartState, new { @class = "form-control" })</td>
                </tr>
                <tr>
                    <td>EndState</td>
                    <td>@Html.EditorFor(model => model.EndState, new { @class = "form-control" })</td>
                </tr>
            </table>
            <div class="panel-footer text-right">
                <a title="Cancel" href="#" onclick="clearConfigPanel();return false;" class="btn btn-warning">Cancel</a>
                @if (ViewBag.Edit == 1)
                {
                    @*<a title="Delete" href="#" onclick="deleteState(@Model.Id);return false;" class="btn btn-danger">Delete</a>*@
                    <a title="Delete" href="#" onclick="showList2('deleteState(@Model.Id)');return false;" class="btn btn-danger">Delete</a>
                    <input type="submit" value="Save" class="btn btn-success" />
                }
            </div>
        </div>
    </div>
}

InFlow_Web/Views/PDesigner/_EditReceiveTransition.cshtml
@model strICT.InFlow.Web.Models.PDesignerViewModels.PD_ReceiveTransition_ViewModel

@using (Html.BeginForm("_EditReceiveTransition", "PDesigner", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="panel panel-primary">
        <div class="panel-heading">Receive Transition @Model.Id</div>
        <div class="panel-body">
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.PD_Process_Id)
            @Html.HiddenFor(model => model.PD_Subject_Id)

            <table class="table table-striped">
                <tr>
                    <td>Message</td>
                    <td>@Html.DropDownListFor(model => model.SelectedMessage, Model.AvailableMessages, new { @class = "form-control" })</td>
                </tr>
            </table>
            <div class="panel-footer text-right">
                <a title="Cancel" href="#" onclick="clearConfigPanel();return false;" class="btn btn-warning">Cancel</a>
                @if (ViewBag.Edit == 1)
                {
                    <input type="submit" value="Save" class="btn btn-success" />
                }
            </div>
        </div>
    </div>
}

InFlow_Web/Views/PDesigner/_EditRegularTransition.cshtml
@model strICT.InFlow.Web.Models.PDesignerViewModels.PD_RegularTransition_ViewModel

@using (Html.BeginForm("_EditRegularTransition", "PDesigner", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="panel panel-primary">
        <div class="panel-heading">Regular Transition @Model.Id</div>
        <div class="panel-body">
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.PD_Process_Id)
            @Html.HiddenFor(model => model.PD_Subject_Id)

            <table class="table table-striped">
                <tr>
                    <td>Name</td>
                    <td>@Html.TextBoxFor(model => model.Name, new { @class = "form-control" })</td>
                </tr>
            </table>
            <div class="panel-footer text-right">
                <a title="Cancel" href="#" onclick="clearConfigPanel();return false;" class="btn btn-warning">Cancel</a>
                @if (ViewBag.Edit == 1)
                { 
                    <input type="submit" value="Save" class="btn btn-success" />
                }
            </div>
        </div>
    </div>
}