InFlow_Web/Models/UserAdministrationViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using strICT.InFlow.Web.Models.Shared;

namespace strICT.InFlow.Web.Models.UserAdministration
{
    public class UserViewModel
    {
        [Required]
        public string Id { get; set; }

        [Required]
        public string UserName { get; set; }

        [Required]
        public List<string> AssignedRoles { get; set; }

        [Required]
        public List<string> NotAssignedRoles { get; set; }

    }

    public class SetUserPasswordViewModel
    {
        [Required]
        public string userId { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

  
     public class ShowGroupsAndRightsViewModel
     {
         public List<ListViewItemModel> Groups { get; set; }

         public List<ListViewItemModel> Roles { get; set; }

         public ShowGroupsAndRightsViewModel()
         {
             Groups = new List<ListViewItemModel>();
             Roles = new List<ListViewItemModel>();
         }

     }

    public class EditGroupViewModel
    {
        [Required]
        public int GroupId { get; set; }

        [Required]
        public string GroupName { get; set; }

        public List<ListViewItemModel> Users { get; set; }

        public List<ListViewItemModel> Roles { get; set; }

        public string[] SelectedUsers { get; set; }

        public string[] SelectedRoles { get; set; }

        public EditGroupViewModel()
        {
            Users = new List<ListViewItemModel>();
            Roles = new List<ListViewItemModel>();
        }
    }

    public class EditRoleViewModel
    {
        [Required]
        public int RoleId { get; set; }

        [Required]
        public string RoleName { get; set; }

        public List<ListViewItemModel> Groups { get; set; }

        public string[] SelectedGroups { get; set; }

        public EditRoleViewModel()
        {
            Groups = new List<ListViewItemModel>();
        }
    }

    


}

InFlow_Web/Controllers/UserAdministrationController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using strICT.InFlow.Db.DataContexts;
using strICT.InFlow.Db.Contracts.InFlow;
using strICT.InFlow.Web.Models.UserAdministration;
using strICT.InFlow.Web.Models.Shared;
using strICT.InFlow.Db.Contracts.Identity;
using strICT.InFlow.Web.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using strICT.InFlow.Web.Helpers;
namespace strICT.InFlow.Web.Controllers
{
    [Authorize(Roles = "ProcessEditor, CompanyAdmin")]
    public class UserAdministrationController : Controller
    {
        private static bool ad = Boolean.Parse(ConfigurationManager.AppSettings["AzureAD"]);


        GraphHelper _graph = new GraphHelper();

        IdentityDb _identityDb = new IdentityDb();
        InFlowDb _inFlowDb = new InFlowDb();
        //
       
        // GET: /UserAdministration/
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "ProcessEditor")]
        public ActionResult GroupsRoles()
        {
            ShowGroupsAndRightsViewModel model = new ShowGroupsAndRightsViewModel();


            _inFlowDb.U_FunctionGroups.ToList().ForEach(g => model.Groups.Add(new ListViewItemModel { Id = g.Id, Name = g.Name }));
            _inFlowDb.U_Roles.ToList().ForEach(r => model.Roles.Add(new ListViewItemModel { Id = r.Id, Name = r.Name }));

            return View(model);
        }

          [Authorize(Roles = "ProcessEditor")]
        public ActionResult Group_EditLocal(int id)
        {
            U_FunctionGroup _functionGroup;
            if (id == -1)
            {
                _functionGroup = new U_FunctionGroup { Id = -1 };
            }
            else
            {
                _functionGroup = _inFlowDb.U_FunctionGroups.Find(id);
            }

            EditGroupViewModel model = new EditGroupViewModel() { GroupId = _functionGroup.Id, GroupName = _functionGroup.Name };

            _functionGroup.Roles.ToList().ForEach(r => model.Roles.Add(new ListViewItemModel() { Id = r.Id, Name = r.Name, Selected = true }));
            _inFlowDb.U_Roles.ToList().Except(_functionGroup.Roles.ToList()).ToList().ForEach(r => model.Roles.Add(new ListViewItemModel() { Id = r.Id, Name = r.Name, Selected = false }));


            List<string> assignedUsers = new List<string>();
            _functionGroup.Users.ToList().ForEach(u => assignedUsers.Add(u.Username));
            assignedUsers.ForEach(u => model.Users.Add(new ListViewItemModel { Name = u, Selected = true }));

            List<string> allUsers = new List<string>();
            _identityDb.Users.ToList().ForEach(u => allUsers.Add(u.UserName));
            // _inFlowDb.U_User_FunctionGroups.ToList().ForEach(u => allUsers.Add(u.Username));

            allUsers.Except(assignedUsers).ToList().ForEach(u => model.Users.Add(new ListViewItemModel { Name = u, Selected = false }));

            return View("Group_Edit",model);
        }
          [Authorize(Roles = "ProcessEditor")]
          public async Task<ActionResult> Group_EditAD(int id)
          {
              U_FunctionGroup _functionGroup;
              if (id == -1)
              {
                  _functionGroup = new U_FunctionGroup { Id = -1 };
              }
              else
              {
                  _functionGroup = _inFlowDb.U_FunctionGroups.Find(id);
              }

              EditGroupViewModel model = new EditGroupViewModel() { GroupId = _functionGroup.Id, GroupName = _functionGroup.Name };

              _functionGroup.Roles.ToList().ForEach(r => model.Roles.Add(new ListViewItemModel() { Id = r.Id, Name = r.Name, Selected = true }));
              _inFlowDb.U_Roles.ToList().Except(_functionGroup.Roles.ToList()).ToList().ForEach(r => model.Roles.Add(new ListViewItemModel() { Id = r.Id, Name = r.Name, Selected = false }));


              List<string> assignedUsers = new List<string>();
              _functionGroup.Users.ToList().ForEach(u => assignedUsers.Add(u.Username));
              assignedUsers.ForEach(u => model.Users.Add(new ListViewItemModel { Name = u, Selected = true }));

              List<string> allUsers = new List<string>();
              List<strICT.InFlow.Web.Models.User> users = (await _graph.getUsers()).ToList<strICT.InFlow.Web.Models.User>();
              users.ForEach(u => allUsers.Add(u.userPrincipalName));
              // _inFlowDb.U_User_FunctionGroups.ToList().ForEach(u => allUsers.Add(u.Username));

              allUsers.Except(assignedUsers).ToList().ForEach(u => model.Users.Add(new ListViewItemModel { Name = u, Selected = false }));

              return View("Group_EditAD", model);
          }

        [Authorize(Roles = "ProcessEditor")]
          public async Task<ActionResult> Group_Edit(int id)
        {
            if (ad)
            {
                return await Group_EditAD(id);   
            }
            else
            {
                return Group_EditLocal(id);
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ProcessEditor")]
        public ActionResult Group_Edit(EditGroupViewModel model)
        {
            U_FunctionGroup _group;

            if (model.GroupId == -1)
            {
                _group = new U_FunctionGroup() { Name = model.GroupName };
                _inFlowDb.U_FunctionGroups.Add(_group);
                _inFlowDb.SaveChanges();
            }
            else
            {
                _group = _inFlowDb.U_FunctionGroups.Find(model.GroupId);
            }

            if(!_group.Name.Equals(model.GroupName))
            {
                _group.Name = model.GroupName;
            }


            //users
            List<string> oldAssignedUsers = new List<string>();
            List<string> newAssignedUsers = new List<string>();

            if (model.SelectedUsers != null)
            {
                newAssignedUsers = new List<string>(model.SelectedUsers);
            }

            _group.Users.ToList().ForEach(u => oldAssignedUsers.Add(u.Username));

            List<string> usersToAssign = new List<string>(newAssignedUsers.Except(oldAssignedUsers));

            List<string> usersToRemove = new List<string>(oldAssignedUsers.Except(newAssignedUsers));

            usersToAssign.ForEach(username => _inFlowDb.U_User_FunctionGroups.Add(new strICT.InFlow.Db.Contracts.InFlow.U_User_FunctionGroup { FunctionGroup = _group, Username = username }));

            foreach(string username in usersToRemove)
            {
                var item = _inFlowDb.U_User_FunctionGroups.First(fg => fg.Username == username && fg.FunctionGroup_Id == _group.Id);
                _inFlowDb.U_User_FunctionGroups.Remove(item);
            }

            //roles
            List<int> oldAssignedRoles = new List<int>();
            List<int> newAssignedRoles = new List<int>();

            if (model.SelectedRoles != null)
            {
                (new List<string>(model.SelectedRoles)).ForEach(id => newAssignedRoles.Add(Int16.Parse(id)));
            }

            _group.Roles.ToList().ForEach(r => oldAssignedRoles.Add(r.Id));

            List<int> rolesToAssign = new List<int>(newAssignedRoles.Except(oldAssignedRoles));

            List<int> rolesToRemove = new List<int>(oldAssignedRoles.Except(newAssignedRoles));

            rolesToAssign.ForEach(role => _group.Roles.Add(_inFlowDb.U_Roles.Find(role)));

            rolesToRemove.ForEach(role => _group.Roles.Remove(_inFlowDb.U_Roles.Find(role)));

            //save and return
            _inFlowDb.SaveChanges();

            return RedirectToAction("GroupsRoles");
        }

        [Authorize(Roles = "ProcessEditor")]
        public ActionResult Group_Delete(int id)
        {
            try
            {
                _inFlowDb.U_User_FunctionGroups.RemoveRange(_inFlowDb.U_User_FunctionGroups.Where(u => u.FunctionGroup_Id == id));
                _inFlowDb.U_FunctionGroups.Remove(_inFlowDb.U_FunctionGroups.Find(id));

                _inFlowDb.SaveChanges();
            }
            catch(Exception e)
            {

            }
            return RedirectToAction("GroupsRoles");
        }

        [Authorize(Roles = "ProcessEditor")]
        public ActionResult Role_Edit(int id)
        {
            U_Role _role;
            if (id == -1)
            {
                _role = new U_Role { Id = -1 };
            }
            else
            {
                _role = _inFlowDb.U_Roles.Find(id);
            }
            

            EditRoleViewModel model = new EditRoleViewModel { RoleId = _role.Id, RoleName = _role.Name };

            _role.FunctionGroups.ToList().ForEach(g => model.Groups.Add(new ListViewItemModel { Id = g.Id, Name = g.Name, Selected = true }));
            _inFlowDb.U_FunctionGroups.ToList().Except(_role.FunctionGroups.ToList()).ToList().ForEach(g => model.Groups.Add(new ListViewItemModel { Id = g.Id, Name = g.Name, Selected = false }));

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ProcessEditor")]
        public ActionResult Role_Edit(EditRoleViewModel model)
        {
            U_Role _role;

            if (model.RoleId == -1)
            {
                _role = new U_Role() { Name = model.RoleName };
                _inFlowDb.U_Roles.Add(_role);
                _inFlowDb.SaveChanges();
            }
            else
            {
                _role = _inFlowDb.U_Roles.Find(model.RoleId);
            }

            if (!_role.Name.Equals(model.RoleName))
            {

InFlow_Web/Views/UserAdministration/Group_Edit.cshtml
@model strICT.InFlow.Web.Models.UserAdministration.EditGroupViewModel

@{
    ViewBag.Title = "Group_Edit";
}

<div class="page-header"> <h1><small>Groups&Roles</small><br />Edit group</h1></div>

@using (Html.BeginForm("Group_Edit", "UserAdministration", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
     
    <div class="row">
        <div class="col-md-4">
           
            <div class="form-group">
                @Html.Label("Name", new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.GroupName, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-md-2 text-right">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>

    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.GroupId, new { Value = Model.GroupId })
    <div class="row">
        <div class="col-md-3">
            <table class="table table-striped">
                <tr>
                    <th>
                        Users
                    </th>
                </tr>
                @foreach (var item in Model.Users)
                {
                    <tr>
                        <td>
                            @{ var optionValue = "User_" + item.Name; }
                            <input type="checkbox"
                                   id="@optionValue"
                                   name="SelectedUsers"
                                   @if (@item.Selected) { @Html.Raw("checked=\"checked\"")  }
                                   value="@item.Name" />
                            <label for="@optionValue">@item.Name</label>
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="col-md-3">
            <table class="table table-striped">
                <tr>
                    <th>
                        Roles
                    </th>
                </tr>
                @foreach (var item in Model.Roles)
                {
                    <tr>
                        <td>
                            @{ var optionValue = "Role_" + item.Id; }
                            <input type="checkbox"
                                   id="@optionValue"
                                   name="SelectedRoles"
                                   @if (@item.Selected) { @Html.Raw("checked=\"checked\"")    }
                                   value="@item.Id" />
                            <label for="@optionValue">@item.Name</label>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InFlow_Web/Views/UserAdministration/Group_EditAD.cshtml
@model strICT.InFlow.Web.Models.UserAdministration.EditGroupViewModel

@{
    ViewBag.Title = "Group_Edit";
}

<div class="page-header"> <h1><small>Groups&Roles</small><br />Edit group</h1></div>

@using (Html.BeginForm("Group_Edit", "UserAdministration", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
     
    <div class="row">
        <div class="col-md-4">
           
            <div class="form-group">
                @Html.Label("Name", new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.GroupName, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-md-2 text-right">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>

    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.GroupId, new { Value = Model.GroupId })
    <div class="row">
        <div class="col-md-3">
            <table class="table table-striped">
                <tr>
                    <th>
                        Users
                    </th>
                </tr>
                @foreach (var item in Model.Users)
                {
                    <tr>
                        <td>
                            @{ var optionValue = "User_" + item.Name; }
                            <input type="checkbox"
                                   id="@optionValue"
                                   name="SelectedUsers"
                                   @if (@item.Selected) { @Html.Raw("checked=\"checked\"")  }
                                   value="@item.Name" />
                            <label for="@optionValue">@item.Name</label>
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="col-md-3">
            <table class="table table-striped">
                <tr>
                    <th>
                        Roles
                    </th>
                </tr>
                @foreach (var item in Model.Roles)
                {
                    <tr>
                        <td>
                            @{ var optionValue = "Role_" + item.Id; }
                            <input type="checkbox"
                                   id="@optionValue"
                                   name="SelectedRoles"
                                   @if (@item.Selected) { @Html.Raw("checked=\"checked\"")    }
                                   value="@item.Id" />
                            <label for="@optionValue">@item.Name</label>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InFlow_Web/Views/UserAdministration/GroupsRoles.cshtml
@model strICT.InFlow.Web.Models.UserAdministration.ShowGroupsAndRightsViewModel

@{
    ViewBag.Title = "GroupsRoles";
}
<div class="page-header"> <h1><small>Administration</small><br />Groups&Roles</h1></div>


<div class="row">
    <div class="col-md-4">
        <table class="table table-striped">
            <tr>
                <th>
                    Groups
                </th>
                <th></th>
            </tr>
            @foreach (var item in Model.Groups)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td class ="text-right">
                        <a href="@Url.Action("Group_Edit", new { id = item.Id })"  class="btn btn-default btn-xs"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="@Url.Action("Group_Delete", new { id = item.Id })" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-minus"></span></a>
                    </td>
                </tr>
            }
        </table>
        <div class="text-right">@Html.ActionLink("New Group", "Group_Edit", new { id = -1 }, new { @class = "btn btn-default" })</div>
    </div>
    <div class="col-md-4">
        <table class="table table-striped">
            <tr>
                <th>
                    Roles
                </th>
                <th></th>
            </tr>
            @foreach (var item in Model.Roles)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td class="text-right">
                        <a href="@Url.Action("Role_Edit", new { id = item.Id })" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="@Url.Action("Role_Delete", new { id = item.Id })" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-minus"></span></a>
                    </td>
                </tr>
            }
        </table>
        <div class="text-right">@Html.ActionLink("New Role", "Role_Edit", new { id = -1 }, new { @class = "btn btn-default" })</div>
    </div>
</div>

InFlow_Web/Views/UserAdministration/Rights.cshtml
@model IEnumerable<strICT.InFlow.Web.Models.UserAdministration.UserViewModel>

@{
    ViewBag.Title = "Rights";
}

<div class="page-header"> <h1><small>Administration</small><br />Users&Rights</h1></div>

<div class="row">
    <div class="col-md-12 text-right">
        @Html.ActionLink("Create New User", "Rights_User_New", new { } , new { @class = "btn btn-default" })
    </div>
</div>
   
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>@Html.DisplayNameFor(model => model.AssignedRoles)</th>
        <th>
            @Html.DisplayNameFor(model => model.NotAssignedRoles)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.Raw("| ")
                @foreach (var role in item.AssignedRoles)
                {
                    @Html.Raw(role + " ")
                    <a href="@Url.Action("Rights_RemoveRoleFromUser", new { id = item.Id, role = role })" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-minus"></span></a>
                    @Html.Raw(" | ")
                }
            </td>
            <td>
                @Html.Raw("| ")
                @foreach (var role in item.NotAssignedRoles)
                {
                    @Html.Raw(role + " ")
                    <a href="@Url.Action("Rights_AddRoleToUser", new { id = item.Id, role = role })" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-plus"></span></a>
                    @Html.Raw(" | ")
                }
            </td>
            <td>
                @Html.ActionLink("Set Password", "Rights_User_SetPassword", new { id = item.Id }, new { @class = "btn btn-default btn-xs" })
                @Html.ActionLink("Delete", "Rights_DeleteUser", new { id = item.Id }, new { @class = "btn btn-default btn-xs" })
            </td>
        </tr>
    }

</table>

InFlow_Web/Views/UserAdministration/RightsAD.cshtml
@model IEnumerable<strICT.InFlow.Web.Models.User>

@{
    ViewBag.Title = "Rights";
}

<div class="page-header"> <h1><small>Administration</small><br />Users&Rights</h1></div>


<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.userPrincipalName)
        </th>
        <th>@Html.DisplayNameFor(model => model.AssignedRoles)</th>
        <th>
            @Html.DisplayNameFor(model => model.NotAssignedRoles)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.displayName (@item.userPrincipalName)
            </td>
            <td>
                @Html.Raw("| ")
                @foreach (var role in item.AssignedRoles)
                {
                    @Html.Raw(role + " ")
                    <a href="@Url.Action("Rights_RemoveRoleFromUserAD", new { id = item.objectId, role = role })" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-minus"></span></a>

                      @Html.Raw(" | ")
                }
            </td>
            <td>
                @Html.Raw("| ")
                @foreach (var role in item.NotAssignedRoles)
                {
                    @Html.Raw(role + " ")
                    <a href="@Url.Action("Rights_AddRoleToUserAD", new { id = item.objectId, role = role })" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-plus"></span></a>
                    @Html.Raw(" | ")
                }
            </td>
       
        </tr>
    }

</table>

InFlow_Web/Views/UserAdministration/Rights_User_New.cshtml
@model strICT.InFlow.Web.Models.RegisterViewModel
@{
    ViewBag.Title = "Register";
}

<div class="page-header"> <h1><small>Users&Rights</small><br />Create new user account</h1></div>

@using (Html.BeginForm("Rights_User_New", "UserAdministration", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary()
    <div class="form-group">
        @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InFlow_Web/Views/UserAdministration/Rights_User_SetPassword.cshtml
@model strICT.InFlow.Web.Models.UserAdministration.SetUserPasswordViewModel

<div class="page-header"> <h1><small>Users&Rights</small><br />Set user password</h1></div>


@using (Html.BeginForm("Rights_User_SetPassword", "UserAdministration", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.userId, new { Value = Model.userId })
    <div class="form-group">
        @Html.LabelFor(m => m.NewPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Set password" class="btn btn-default" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InFlow_Web/Views/UserAdministration/Role_Edit.cshtml
@model strICT.InFlow.Web.Models.UserAdministration.EditRoleViewModel

@{
    ViewBag.Title = "Role_Edit";
}

<div class="page-header"> <h1><small>Groups&Roles</small><br />Edit group</h1></div>

@using (Html.BeginForm("Role_Edit", "UserAdministration", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.RoleName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.RoleName, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-md-1 text-right">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>

  if (!System.Configuration.ConfigurationManager.AppSettings["AzureAD"].Equals("true") || true)
        {
            @Html.AntiForgeryToken()
        }
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.RoleId, new { Value = Model.RoleId })
    <div class="row">
        <div class="col-md-4">
            <table class="table table-striped">
                <tr>
                    <th>
                        Groups
                    </th>
                </tr>
                @foreach (var item in Model.Groups)
                {
                    <tr>
                        <td>
                            @{ var optionValue = "User_" + item.Name; }
                            <input type="checkbox"
                                   id="@optionValue"
                                   name="SelectedGroups"
                                   @if (@item.Selected) { @Html.Raw("checked=\"checked\"")    }
                                   value="@item.Id" />
                            <label for="@optionValue">@item.Name</label>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}






@{
    ViewBag.Title = "Role_Edit";
}