InFlow_Web/Models/SharedViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace strICT.InFlow.Web.Models.Shared
{

    public class ListViewItemModel
    {

        public int Id { get; set; }

        public string Name { get; set; }
         
        public bool Selected { get; set; }
    }
}

InFlow_Web/Controllers/JobsController.cs
using strICT.InFlow.Db.DataContexts;
using strICT.InFlow.Web.Helpers;
using strICT.InFlow.Web.Models.JobsViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace strICT.InFlow.Web.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {
        InFlowDb _inflowDb = new InFlowDb();
        IJobsHelper helper = new JobsHelper();
        public PartialViewResult TaskList()
        {
            return PartialView("_TaskList", getPTVM());
        }

        public List<ProcessTasksViewModel> getPTVM()
        {
            List<TaskListItemViewModel> tasks = helper.getOpenTaskListForUser(User.Identity.Name);

            List<strICT.InFlow.Web.Models.JobsViewModels.ProcessTasksViewModel> model = new List<ProcessTasksViewModel>();

            Dictionary<int, ProcessTasksViewModel> temp = new Dictionary<int, ProcessTasksViewModel>();

            foreach (var task in tasks)
            {
                if (!temp.ContainsKey(task.ProcessId))
                {
                    var p = _inflowDb.P_Processes.Find(task.ProcessId);
                    temp.Add(task.ProcessId, new ProcessTasksViewModel { ProcessId = task.ProcessId, ProcessName = p.WS_Project.Name, Tasks = new List<TaskListItemViewModel>(), Version = p.WS_Project_Version, Description = p.ProcessInfo });
                }
                temp[task.ProcessId].Tasks.Add(task);
            }

            foreach (var i in temp)
            {
                i.Value.Tasks = i.Value.Tasks.OrderBy(x => x.OrderId).ThenBy(x => x.Id).ToList();
                model.Add(i.Value);
            }
            return model;
        }

        // GET: /Jobs/
        public ActionResult Index(int id)
        {
            ViewBag.Id = id;

           

            return View(getPTVM());
        }

         [OutputCache(Location = System.Web.UI.OutputCacheLocation.None)]
        public ActionResult SetStateAsSeen(int id, string mode)
        {
            helper.setTaskAsSeen(id, User.Identity.Name);
            if (mode.Equals("mobile"))
            {
                return RedirectToAction("Mobile", new { id = id });
            }
            else
            {
                return RedirectToAction("Index", new { id = -1 });
            }
        }

         [OutputCache(Location = System.Web.UI.OutputCacheLocation.None)]
        public ActionResult _FunctionState(int id, string mode)
        {
            ViewBag.TaskId = id;
            FunctionTaskViewModel model = helper.getFunctionTask(id, User.Identity.Name);
            model.ViewMode = mode;
            return PartialView(model);
        }

        public ActionResult Feedback()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _FunctionState(FunctionTaskViewModel model)
        {
            helper.setFunctionTask(model, User.Identity.Name);

            if (model.ViewMode.Equals("mobile"))
            {
                return RedirectToAction("Mobile", new { id = model.Id });
            }
            else
            {
                return RedirectToAction("Index", new { id = -1 });
            }
        }

         [OutputCache(Location = System.Web.UI.OutputCacheLocation.None)]
        public ActionResult _SendState(int id, string mode)
        {
   
            ViewBag.TaskId = id;
            SendTaskViewModel model = helper.getSendTask(id, User.Identity.Name);
            model.ViewMode = mode;
            return PartialView(model);
        }
        public ActionResult Mobile(int id) {

           //strICT.InFlow.Db.Contracts.InFlow.T_Task t = _inflowDb.T_Tasks.Find(id);
            
            // SendTaskViewModel model = helper.getSendTask(id, User.Identity.Name);
            ViewBag.Id = id;
            return View();
        }

        [OutputCache(Location = System.Web.UI.OutputCacheLocation.None)]
        public ActionResult _State(int id, string mode)
        {
            string type = _inflowDb.T_Tasks.Find(id).Type;

            if (type.Equals("F"))
                return RedirectToAction("_FunctionState", new { id = id, mode = mode });

            else if (type.Equals("S"))
                return RedirectToAction("_SendState", new { id = id, mode = mode });

            else if (type.Equals("R"))
                return RedirectToAction("_ReceiveState", new { id = id, mode = mode });

            else
                return null;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _SendState(SendTaskViewModel model)
        {
            helper.setSendTask(model, User.Identity.Name);
            if (model.ViewMode.Equals("mobile"))
            {
                return RedirectToAction("Mobile", new { id = model.Id });
            }
            else
            {
                return RedirectToAction("Index", new { id = -1 });
            }
        }

         [OutputCache(Location = System.Web.UI.OutputCacheLocation.None)]
        public ActionResult _ReceiveState(int id, string mode)
        {      
            ViewBag.TaskId = id;
            ReceiveTaskViewModel model = helper.getReceiveTask(id, User.Identity.Name);
            model.ViewMode = mode;
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _ReceiveState(ReceiveTaskViewModel model)
        {
            helper.setReceiveTask(model, User.Identity.Name);
            if (model.ViewMode.Equals("mobile"))
            {
                return RedirectToAction("Mobile", new { id = model.Id });
            }
            else
            {
                return RedirectToAction("Index", new { id = -1 });
            }
        }



        public ActionResult NewProcess(int id)
        {
            if (id == -1)
            {
                return View(helper.getStartProcesses(User.Identity.Name));
            }
            else
            {
                helper.startProcess(id, User.Identity.Name);
                return RedirectToAction("Index", new { id = -1 });
            }
        }



        public ActionResult AnsweredTasks(int id)
        {
            ViewBag.Id = id;

            List<TaskListItemViewModel> tasks = helper.getAnsweredTaskListForUser(User.Identity.Name);

            List<strICT.InFlow.Web.Models.JobsViewModels.ProcessTasksViewModel> model = new List<ProcessTasksViewModel>();

            Dictionary<int, ProcessTasksViewModel> temp = new Dictionary<int, ProcessTasksViewModel>();

            foreach(var task in tasks)
            {
                if(!temp.ContainsKey(task.ProcessId))
                {
                    var p = _inflowDb.P_Processes.Find(task.ProcessId);
                    temp.Add(task.ProcessId, new ProcessTasksViewModel { ProcessId = task.ProcessId, ProcessName = p.WS_Project.Name, Tasks = new List<TaskListItemViewModel>(), Version = p.WS_Project_Version, Description = p.ProcessInfo  });
                }
                temp[task.ProcessId].Tasks.Add(task);
            }

            foreach(var i in temp)
            {
                i.Value.Tasks = i.Value.Tasks.OrderByDescending(x => x.DateTimeSubmitted).ToList();
                model.Add(i.Value);
            }


            return View(model);
        }
    }

}

InFlow_Web/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using strICT.InFlow.Db.DataContexts;
using strICT.InFlow.Db.Contracts.InFlow;
using strICT.InFlow.Web.Models;
using strICT.InFlow.Web.Models.ProjectViewModels;
using strICT.InFlow.Web.Helpers;
using strict.InFlow.Designer.Db.Contracts;
using strict.InFlow.Designer.Db;
using System.Xml.Serialization;
using System.Xml;


namespace strICT.InFlow.Web.Controllers
{
    [Authorize(Roles = "ProcessEditor")]
    public class ProjectController : Controller
    {
        InFlowDb _db = new InFlowDb();
        PDesignerDb _pDesignerDB = new PDesignerDb();
        //
        // GET: /Project/
        /*public ActionResult Index()
        {
            return View();
        }*/
        public ActionResult Index(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public IEnumerable<U_Role> AllRoles()
        {
            IEnumerable<U_Role> roles = _db.U_Roles;
            List<U_Role> lroles = roles.ToList();
            var emptyRole = new U_Role();
            emptyRole.Id = -1;
            emptyRole.Name = "-";
            lroles.Add(emptyRole);
            return lroles;
        }
        public IEnumerable<WS_Folder> RootFolders()
        {
            var model = from f in _db.WS_Folders
                        where f.Parent == null
                        select f;
            return model;

        }

        public ActionResult Unlock(int processid, int projectId)
        {
            _pDesignerDB.PD_Processes.Find(processid).LockedBy = null;
            _pDesignerDB.SaveChanges();

            return RedirectToAction("Index", new { id = projectId });
        }

        public ActionResult DeleteFolder(int folderId)
        {

            _db.WS_Folders.Remove(_db.WS_Folders.Find(folderId));
            _db.SaveChanges();
            return View("Index");
        }

        public ActionResult DeleteProject(int projectId)
        {
            var project = _db.WS_Projects.Find(projectId);
            project.Deleted = true;

            _db.SaveChanges();
            return View("Index");
        }

        [Authorize(Roles = "CompanyAdmin")]
        public ActionResult DeleteProjectFull(int projectId)
        {
            int count = _db.P_Processes.Count(result => result.WS_ProjectId == projectId);

            if (count == 0)
            {
                var processes = _db.WS_ModelVersions.Where(r => r.WS_ProjectId == projectId);
                foreach(var p in processes)
                {
                    DbHelper.fullyDeletePD_Process(_pDesignerDB, p.PD_ProcessId);
                }

                _db.WS_Projects.Remove(_db.WS_Projects.Find(projectId));
                _db.SaveChanges();
                return View("Index");
            }
            else
            {
                ViewBag.Error = "Referenced Processes in backend!";

                return View("Error");
            }
        }

        public ActionResult _CreateFolder(int folderId)
        {
            WS_Folder model;
            if (folderId > 0)
            {
                model = _db.WS_Folders.Find( folderId );
            }
            else
            {
                model = new WS_Folder() { Parent_Id = null };
            }
            return PartialView(model);

        }

        public ActionResult _ImportBPMN()
        {
            var m = new BPMNImportViewModel();
            List<WS_Folder> folderlist = _db.WS_Folders.Where(f => f.Parent_Id == null).ToList<WS_Folder>();
           

            m.folder = from c in folderlist
                       select new SelectListItem
                       {
                           
                           Text = c.Name,
                           Value = c.Id.ToString()
                       };
          
            return PartialView(m);

        }

        [HttpPost]
        public ActionResult ImportBPMN(BPMNImportViewModel model)
        {
            model.description = "Imported from BPMN";
           ZipArchive a = new ZipArchive(model.zipfile.InputStream);
           List<definitions> imports = new List<definitions>();

           foreach (ZipArchiveEntry entry in a.Entries)
           {
               if (entry.FullName.EndsWith(".bpmn", StringComparison.OrdinalIgnoreCase))
               {

                   StreamReader reader = new StreamReader(entry.Open());

             
                   XmlRootAttribute xRoot = new XmlRootAttribute();
                   xRoot.ElementName = "definitions";
                   xRoot.Namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL";
                   xRoot.IsNullable = true;
                   XmlSerializer serializer = new XmlSerializer(typeof(definitions), xRoot);
                   XmlReader xRdr = XmlReader.Create(reader);
                   definitions import = (definitions)serializer.Deserialize(xRdr);
                //   BPMNImport import = (BPMNImport)serializer.Deserialize(new XmlTextReader(reader));


                imports.Add(import);
               }
           }

           

          
           foreach (definitions i in imports)
           {
               WS_Project p = new WS_Project();

               p.Name =i.BPMNDiagram.name;
               p.Description = model.description;
               p.Folder_Id = model.folderId;

               this.CreateProject(p);

               int pd_id = p.ModelVersions.FirstOrDefault().PD_ProcessId;


               PD_Process pdp = _pDesignerDB.PD_Processes.Find(pd_id);
               int n = 50;
               int c = 0;
               int t = 50;
               foreach (var x in i.collaboration.participant)
               {
                   PD_Subject s = new PD_Subject();
               
                   s.Name = x.name;
                   if (c == 10) {
                       t += 400;
                       c = 0;
                       n = 50;
                   }
                   s.PositionLeft = n;

                   s.PositionTop = t;
                   c++;
                   n += 200;
                   s.CanvasHeight = 1000;
                   s.CanvasWidth = 1000;
                   s.Id = IdHelper.getSubjectId(_pDesignerDB, pdp.Id);

                    pdp.Subjects.Add(s);
                    pdp.CanvasHeight = 200 + t;
                    if (s.PositionLeft > pdp.CanvasWidth)
                    {
                        pdp.CanvasWidth = s.PositionLeft;
                    }
               }
               if (i.collaboration.messageFlow != null) { 
               foreach (var x in i.collaboration.messageFlow)
               {
                PD_MessageType pdm = new PD_MessageType();
                pdm.PD_Process_Id = pdp.Id;
                pdm.Id = IdHelper.getMessageTypeId(_pDesignerDB, pdp.Id);
                pdm.Name = x.name;
                pdp.MessageTypes.Add(pdm);

               /* try { 
                PD_Message m = new PD_Message();
                m.Id = IdHelper.getMessageId(_pDesignerDB, pdp.Id);
           
                
                string fname = i.collaboration.participant.Where(s => s.id.Equals(x.sourceRef)).FirstOrDefault().name;
                m.From = pdp.Subjects.Where(y => y.Name.Equals(fname)).FirstOrDefault().Id;
                m.To = pdp.Subjects.Where(y => y.Name.Equals(i.collaboration.participant.Where(s => s.id.Equals(x.targetRef)).FirstOrDefault().name)).FirstOrDefault().Id;
                m.PD_MessageType_Id = pdm.Id;
                pdp.Messages.Add(m);
                   }
                catch (Exception e)
                {

                }*/
               }
               }
               foreach (var x in i.process)
               {
                   PD_Subject pds = pdp.Subjects.Where(z => z.Name.Equals(x.name)).FirstOrDefault();
                   foreach (var y in x.Items)
                   {
                       PD_FunctionState pdf = new PD_FunctionState();
                      const string pre = "strICT.InFlow.Web.Models.";
                       Type w = y.GetType();
                       switch (w.FullName)
                       {
                           case pre + "definitionsProcessAssociation":

                               definitionsProcessAssociation var1 = (definitionsProcessAssociation)y;

                           break;
                           case pre + "definitionsProcessDataStoreReference":

                           definitionsProcessDataStoreReference var2 = (definitionsProcessDataStoreReference)y;

                           break;
                           case pre + "definitionsProcessIntermediateCatchEvent":

                           definitionsProcessIntermediateCatchEvent var3 = (definitionsProcessIntermediateCatchEvent)y;
                           pdf = new PD_FunctionState();
                           pdf.Name = var3.name;
                           pdf.PD_Process_Id = pdp.Id;
                           pdf.PD_Subject_Id = pds.Id;
                           pdf.Type = PD_StateTypes.FunctionState;
                           pdf.Id = IdHelper.getStateId(_pDesignerDB, pdp.Id, pds.Id);
                           if (var3.incoming == null)
                           {
                               pdf.StartState = true;
                           }
                           if (var3.outgoing == null)
                           {
                               pdf.EndState = true;
                           }

                           pds.States.Add(pdf);

                           
                           break;
                           case pre + "definitionsProcessIntermediateThrowEvent":

                           definitionsProcessIntermediateThrowEvent var4 = (definitionsProcessIntermediateThrowEvent)y;
                                       pdf = new PD_FunctionState();

InFlow_Web/Views/Shared/ContactForm.cshtml
@model strICT.InFlow.Web.Models.ContactViewModel
<h2>Sign up for a free trial!</h2>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Fill out this form to apply for a free trial version of our software. </h3>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("Contact","Contact",FormMethod.Post, new { @class = "form-horizontal", role = "form"}))
                {

                    @Html.ValidationSummary(true)
                    <fieldset>
                        <div class="form-group" style="margin-left:5px;">
                           Your E-Mail*
                            @Html.TextBoxFor(model => model.Mail, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Mail)
                        </div>
                        <div class="form-group" style="margin-left:5px;">
                            Your Name*

                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name)
                        </div>
                        <div class="form-group" style="margin-left:5px;">
                            Your Company or Organization*

                            @Html.TextBoxFor(model => model.Company, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Company)
                        </div>
                        <div class="form-group" style="margin-left:5px;">
                            Your Promotion Code 

                            @Html.TextBoxFor(model => model.PromoCode, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.PromoCode)
                        </div>
                        <small>* - required field</small>
                        <p>
                            <button type="submit" class="btn btn-default">Submit</button>
                        </p>
                    </fieldset>
                }
            </div>
        </div>
        </div>
  
</div>

InFlow_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>InFlow - @ViewBag.Title</title>
   
    @RenderSection("stylesheets", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load('visualization', '1.0', { packages: ['corechart'] });
    </script>
    <link rel="stylesheet" type="text/css" media="all"
          href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("InFlow", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("ProcessEditor"))
                    {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Projects<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Processes", "Index", "Project", new { id = -1 }, new { })</li>
                            @if (User.IsInRole("CompanyAdmin"))
                            {
                                <li>@Html.ActionLink("Published Processes", "Index", "ManageBackend", new { projectId = -1 }, new { })</li>
                            }
                            <li>@Html.ActionLink("Business Objects", "Index", "ManageBOs", new { }, new { }) </li>
                        </ul>
                    </li>
                    }
                  
                    @if (User.IsInRole("ProcessEditor") || User.IsInRole("CompanyAdmin"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administration<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                @if (User.IsInRole("ProcessEditor"))
                                {
                                    <li>@Html.ActionLink("Groups&Roles", "GroupsRoles", "UserAdministration")</li>
                                }
                                @if (User.IsInRole("CompanyAdmin"))
                                {
                                    <li>@Html.ActionLink("User&Rights", "Rights", "UserAdministration")</li>
                                }
                            </ul>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("My Jobs", "Index", "Jobs", new { id = -1 }, new { })</li>
                    }
                    @if (User.IsInRole("ProcessEditor") || User.IsInRole("CompanyAdmin"))
                    {
                        <li>@Html.ActionLink("Reporting", "Index", "Reporting")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <a href="http://www.strict-solutions.com">StrICT-Solutions GmbH</a></p>
        </footer>
    </div>
 
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $.ajaxSetup({ cache: false });
    </script>
</body>
</html>